### ISSUE TITLE
Bug: Currency Not Visible in Transaction List

### ISSUE THREAD

**Issue by SamiKhanDev** [furqanullah717/expense-tracker-android#8]
Investigate and resolve an issue where the currency symbol or name is not displayed in the transaction list. This bug affects the visibility of financial data, leading to potential confusion for users reviewing their transactions. The fix should ensure that the correct currency format is consistently shown across all relevant UI components.

**Comment by furqanullah717** [comment]
https://github.com/furqanullah717/expense-tracker-android/pull/11
